apiVersion: v1
kind: Service
metadata:
  name: agent2-svc
  namespace: petragentic
spec:
  selector:
    app: agent2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP
