apiVersion: v1
kind: Service
metadata:
  name: agent1-svc
  namespace: petragentic
spec:
  selector:
    app: agent1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
