apiVersion: v1
kind: Service
metadata:
  name: orchestrate-svc
  namespace: petragentic
spec:
  selector:
    app: orchestrate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: ClusterIP
